### ISSUE TITLE
Duplicate folder icons

### ISSUE THREAD

**Issue by tbr00** [feinstaub/firefox_addon_local_filesystem_links#68] opened 2016-05-31 00:07 UTC
The add-on is working for me, but if I navigate away from the page containing the file link, then hit the browser back button, I see two folder icons side by side.  Each time I repeat this another one is added.

**Comment by AWolf81** [comment] 2016-05-31 18:19
Thanks for your feedback. I think that should be fixed with the next released version. I can't see this issue in lastest master version. Maybe the fixed issue #56 is related.

If this is still happening with the next version please add another comment here and we'll do further investigations. (Next version will be available as soon as we're closing localization pull-request.)

**Comment by AWolf81** [comment] 2016-07-15 23:09
We're soon releasing the next version where it should be fixed. So we can close this issue. 

Please leave a comment here if the issue is still present at version v0.99.45.

**Closed by AWolf81** 2016-07-15 23:09 UTC
